# Generated by Django 3.0.6 on 2020-06-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('interval', models.PositiveIntegerField(verbose_name='Отправить через,с')),
                ('subject', models.CharField(max_length=50, verbose_name='Тема письма')),
                ('message', models.TextField(max_length=500, verbose_name='Сообщение')),
                ('send_to', models.EmailField(max_length=254, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
